name: Deploy

on:
  workflow_run:
    workflows: [Node.js CI]
    types: [completed]
    branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: executing remote build process
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: ./websites/nachoAPI.sh
